# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LaserGUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer
from LaserComms import readLaser, sendCmd

global GUIDE_BEAM_STATE 
global LASER_BEAM_STATE

GUIDE_BEAM_STATE = 0
LASER_BEAM_STATE = 0

class Ui_LaserController(object):
    def setupUi(self, LaserController):
        LaserController.setObjectName("LaserController")
        LaserController.resize(571, 281)
        LaserController.setMaximumSize(QtCore.QSize(1500, 325))
        LaserController.setStyleSheet("font: 75 8pt \"Arial\";")
        self.horizontalLayoutWidget = QtWidgets.QWidget(LaserController)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 481, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.powerSliderLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.powerSliderLayout.setContentsMargins(0, 0, 0, 0)
        self.powerSliderLayout.setObjectName("powerSliderLayout")
        self.powerSlider = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.powerSlider.setMaximum(500)
        self.powerSlider.setProperty("value", 0)
        self.powerSlider.setSliderPosition(0)
        self.powerSlider.setOrientation(QtCore.Qt.Horizontal)
        self.powerSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.powerSlider.setTickInterval(10)
        self.powerSlider.setObjectName("powerSlider")
############################################### POWER SLIDER FUNCTION ##########################################################
        self.powerSlider.valueChanged.connect(self.powerSliderInput)
        self.powerSliderLayout.addWidget(self.powerSlider)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(LaserController)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(500, 50, 61, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.powerDisplayLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.powerDisplayLayout.setContentsMargins(0, 0, 0, 0)
        self.powerDisplayLayout.setObjectName("powerDisplayLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.powerDisplayLayout.addItem(spacerItem)
        self.powerReading = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.powerReading.setText("")
        self.powerReading.setObjectName("powerReading")
############################################## POWER DIRECT INPUT FUNCTION #####################################################
        self.powerReading.returnPressed.connect(self.powerReadingInput)
        self.powerDisplayLayout.addWidget(self.powerReading)
        self.wattLabel1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.wattLabel1.setObjectName("wattLabel1")
        self.powerDisplayLayout.addWidget(self.wattLabel1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.powerDisplayLayout.addItem(spacerItem1)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(LaserController)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.titleLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.titleLayout.setContentsMargins(0, 0, 0, 0)
        self.titleLayout.setObjectName("titleLayout")
        self.titleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.titleLabel.setObjectName("titleLabel")
        self.titleLayout.addWidget(self.titleLabel)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(LaserController)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(300, 100, 111, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.guideBeamLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.guideBeamLayout.setContentsMargins(0, 0, 0, 0)
        self.guideBeamLayout.setObjectName("guideBeamLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.guideBeamLayout.addItem(spacerItem2)
        self.GBLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.GBLabel.setStyleSheet("font: 75 8pt \"Arial\";")
        self.GBLabel.setTextFormat(QtCore.Qt.PlainText)
        self.GBLabel.setScaledContents(True)
        self.GBLabel.setObjectName("GBLabel")
        self.guideBeamLayout.addWidget(self.GBLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.guideBeamBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.guideBeamBtn.setObjectName("guideBeamBtn")
        self.guideBeamBtn.setFixedWidth(60)
        self.guideBeamBtn.setStyleSheet('QPushButton{background-color: #ff0000; color: white;}')
########################################### START GUIDE BEAM FUNCTION #####################################################
        self.guideBeamBtn.clicked.connect(self.startGuideBeam)
        self.guideBeamLayout.addWidget(self.guideBeamBtn, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.guideBeamLayout.addItem(spacerItem3)
        self.formLayoutWidget = QtWidgets.QWidget(LaserController)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 100, 281, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.laserReadLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.laserReadLayout.setContentsMargins(0, 0, 0, 0)
        self.laserReadLayout.setObjectName("laserReadLayout")
        self.deliveredPowerLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.deliveredPowerLabel.setStyleSheet("font: 75 8pt \"Arial\";")
        self.deliveredPowerLabel.setObjectName("deliveredPowerLabel")
        self.laserReadLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.deliveredPowerLabel)
        self.temperatureLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.temperatureLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.temperatureLabel.setStyleSheet("\n""font: 75 8pt \"Arial\";")
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.laserReadLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.temperatureLabel)
        self.deliveredPowerEntry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.deliveredPowerEntry.setEnabled(True)
        self.deliveredPowerEntry.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.deliveredPowerEntry.setStyleSheet("font: 75 8pt \"Arial\";")
        self.deliveredPowerEntry.setObjectName("deliveredPowerEntry")
        self.deliveredPowerEntry.setFixedWidth(60)
        self.deliveredPowerEntry.setReadOnly(True)
        self.laserReadLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.deliveredPowerEntry)
        self.temperatureEntry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.temperatureEntry.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.temperatureEntry.setStyleSheet("font: 75 8pt \"Arial\";")
        self.temperatureEntry.setText("")
        self.temperatureEntry.setObjectName("temperatureEntry")
        self.temperatureEntry.setFixedWidth(60)
        self.temperatureEntry.setReadOnly(True)
        self.laserReadLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.temperatureEntry)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.laserReadLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.laserReadLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.laserReadLayout.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        self.deliveredPowerEntry.raise_()
        self.temperatureEntry.raise_()
        self.deliveredPowerLabel.raise_()
        self.temperatureLabel.raise_()
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(LaserController)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(420, 100, 111, 91))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.laserBeamLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.laserBeamLayout.setContentsMargins(0, 0, 0, 0)
        self.laserBeamLayout.setObjectName("laserBeamLayout")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.laserBeamLayout.addItem(spacerItem7)
        self.GBLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.GBLabel_2.setStyleSheet("font: 75 8pt \"Arial\";")
        self.GBLabel_2.setTextFormat(QtCore.Qt.PlainText)
        self.GBLabel_2.setScaledContents(True)
        self.GBLabel_2.setObjectName("GBLabel_2")
        self.laserBeamLayout.addWidget(self.GBLabel_2, 0, QtCore.Qt.AlignHCenter)
        self.laserBeamBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.laserBeamBtn.setObjectName("laserBeamBtn")
        self.laserBeamBtn.setFixedWidth(60)
        self.laserBeamBtn.setStyleSheet('QPushButton{background-color: #ff0000; color: white;}')
################################################ START LASER BEAM FUNCTION ####################################################
        self.laserBeamBtn.clicked.connect(self.startLaserBeam)
        self.laserBeamLayout.addWidget(self.laserBeamBtn, 0, QtCore.Qt.AlignHCenter)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.laserBeamLayout.addItem(spacerItem8)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(LaserController)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 190, 531, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.cmdLineLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.cmdLineLayout.setContentsMargins(0, 0, 0, 0)
        self.cmdLineLayout.setObjectName("cmdLineLayout")
        self.cmdLineLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.cmdLineLabel.setObjectName("cmdLineLabel")
        self.cmdLineLayout.addWidget(self.cmdLineLabel)
        self.cmdlineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.cmdlineEdit.setObjectName("cmdlineEdit")
###################################### COMMAND LINE INPUT FUNCTION ##########################################################
        self.cmdlineEdit.returnPressed.connect(self.cmdInput)
        self.cmdLineLayout.addWidget(self.cmdlineEdit)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(LaserController)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 230, 531, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.responseLineLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.responseLineLayout.setContentsMargins(0, 0, 0, 0)
        self.responseLineLayout.setObjectName("responseLineLayout")
        self.responseLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.responseLabel.setObjectName("responseLabel")
        self.responseLineLayout.addWidget(self.responseLabel)

        self.retranslateUi(LaserController)
        QtCore.QMetaObject.connectSlotsByName(LaserController)

############################################## READ TEMPERATURE AND LASER POWER ###############################################
        self.timer = QTimer()
        self.timer.setInterval(100)
        self.timer.start()
        self.timer.timeout.connect(self.readValues)

    def retranslateUi(self, LaserController):
        _translate = QtCore.QCoreApplication.translate
        LaserController.setWindowTitle(_translate("LaserController", "Laser GUI"))
        self.wattLabel1.setText(_translate("LaserController", "W"))
        self.titleLabel.setText(_translate("LaserController", "Laser Power (0 - 500 Watts):"))
        self.GBLabel.setText(_translate("LaserController", "Guide Beam:"))
        self.guideBeamBtn.setText(_translate("LaserController", "OFF"))
        self.deliveredPowerLabel.setText(_translate("LaserController", "Laser Delivered Power (W):"))
        self.temperatureLabel.setText(_translate("LaserController", "Temperature (Celsius):"))
        self.GBLabel_2.setText(_translate("LaserController", "Laser Beam:"))
        self.laserBeamBtn.setText(_translate("LaserController", "OFF"))
        self.cmdLineLabel.setText(_translate("LaserController", "Command Line: "))
        self.responseLabel.setText(_translate("LaserController", "Response: "))

    def powerSliderInput(self):
        inputPower = self.powerSlider.value()
        self.powerReading.setText(str(inputPower))
        inputPowerPercent = round((inputPower/5),1)
        msg = (f"SDC {str(inputPowerPercent)}")
        sendCmd(msg)

    def powerReadingInput(self):
        inputPower = self.powerReading.text()
        self.powerSlider.setValue(int(inputPower))
        inputPowerPercent = round((int(inputPower)/5),1)
        msg = (f"SDC {str(inputPowerPercent)}")
        sendCmd(msg)

    def readValues(self):
        deliveredPower = readLaser("ROP") # ROP reds the output power of the laser
        temperature = readLaser("RCT") # RCT reds the internal temperature of the laser
        self.deliveredPowerEntry.setText(deliveredPower)
        self.temperatureEntry.setText(temperature)

    def cmdInput(self):
        msg = self.cmdlineEdit.text()
        response = sendCmd(msg)
        self.cmdlineEdit.clear()
        self.responseLabel.setText(f"Response: {response}")

    def startGuideBeam(self):
        global GUIDE_BEAM_STATE
        if GUIDE_BEAM_STATE == 0:
            GUIDE_BEAM_STATE = 1
            self.guideBeamBtn.setStyleSheet('QPushButton{background-color: #00ff00; color: black;}')
            self.guideBeamBtn.setText("ON")
            sendCmd("ABN")
        else:
            GUIDE_BEAM_STATE = 0
            self.guideBeamBtn.setStyleSheet('QPushButton{background-color: #ff0000; color: white;}')
            self.guideBeamBtn.setText("OFF")
            sendCmd("ABF")

    def startLaserBeam(self):
        global LASER_BEAM_STATE
        if LASER_BEAM_STATE == 0:
            LASER_BEAM_STATE = 1
            self.laserBeamBtn.setStyleSheet('QPushButton{background-color: #00ff00; color: black;}')
            self.laserBeamBtn.setText("ON")
            sendCmd("EMON")
        else:
            LASER_BEAM_STATE = 0
            self.laserBeamBtn.setStyleSheet('QPushButton{background-color: #ff0000; color: white;}')
            self.laserBeamBtn.setText("OFF")
            sendCmd("EMOFF")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LaserController = QtWidgets.QWidget()
    ui = Ui_LaserController()
    ui.setupUi(LaserController)
    LaserController.show()
    sys.exit(app.exec_())
