# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'L-IR-GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from ast import Try
from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import numpy as np
import matplotlib.pyplot as plt
import LaserComms
import IRCam

# Global variables to control button states
global GUIDE_BEAM_STATE 
global LASER_BEAM_STATE
global CAM_CONNECT_STATE
global PLOT_BUTTON_STATE

GUIDE_BEAM_STATE = 0
LASER_BEAM_STATE = 0
CAM_CONNECT_STATE = 0
PLOT_BUTTON_STATE = 0

class Ui_LIRGUI(object):
    # UI layout auto generated
    def setupUi(self, LIRGUI):
        LIRGUI.setObjectName("LIRGUI")
        LIRGUI.resize(900, 281)
        LIRGUI.setMaximumSize(QtCore.QSize(1500, 325))
        LIRGUI.setStyleSheet("font: 75 8pt \"Arial\";")
        self.horizontalLayoutWidget = QtWidgets.QWidget(LIRGUI)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 481, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.powerSliderLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.powerSliderLayout.setContentsMargins(0, 0, 0, 0)
        self.powerSliderLayout.setObjectName("powerSliderLayout")
        self.powerSlider = QtWidgets.QSlider(self.horizontalLayoutWidget)
        self.powerSlider.setMaximum(500)
        self.powerSlider.setProperty("value", 0)
        self.powerSlider.setSliderPosition(0)
        self.powerSlider.setOrientation(QtCore.Qt.Horizontal)
        self.powerSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.powerSlider.setTickInterval(10)
        self.powerSlider.setObjectName("powerSlider")
        self.powerSliderLayout.addWidget(self.powerSlider)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(LIRGUI)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(500, 50, 71, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.powerDisplayLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.powerDisplayLayout.setContentsMargins(0, 0, 0, 0)
        self.powerDisplayLayout.setObjectName("powerDisplayLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.powerDisplayLayout.addItem(spacerItem)
        self.powerReading = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.powerReading.setText("")
        self.powerReading.setObjectName("powerReading")
        self.powerDisplayLayout.addWidget(self.powerReading)
        self.wattLabel1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.wattLabel1.setObjectName("wattLabel1")
        self.powerDisplayLayout.addWidget(self.wattLabel1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.powerDisplayLayout.addItem(spacerItem1)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(LIRGUI)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 301, 21))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.laserTitleLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.laserTitleLayout.setContentsMargins(0, 0, 0, 0)
        self.laserTitleLayout.setObjectName("laserTitleLayout")
        self.laserTitleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.laserTitleLabel.setObjectName("laserTitleLabel")
        self.laserTitleLayout.addWidget(self.laserTitleLabel)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(LIRGUI)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(300, 100, 111, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.guideBeamLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.guideBeamLayout.setContentsMargins(0, 0, 0, 0)
        self.guideBeamLayout.setObjectName("guideBeamLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.guideBeamLayout.addItem(spacerItem2)
        self.GBLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.GBLabel.setStyleSheet("font: 75 8pt \"Arial\";")
        self.GBLabel.setTextFormat(QtCore.Qt.PlainText)
        self.GBLabel.setScaledContents(True)
        self.GBLabel.setObjectName("GBLabel")
        self.guideBeamLayout.addWidget(self.GBLabel, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.guideBeamBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.guideBeamBtn.setObjectName("guideBeamBtn")
        self.guideBeamLayout.addWidget(self.guideBeamBtn, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.guideBeamLayout.addItem(spacerItem3)
        self.formLayoutWidget = QtWidgets.QWidget(LIRGUI)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 100, 281, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.laserReadLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.laserReadLayout.setContentsMargins(0, 0, 0, 0)
        self.laserReadLayout.setObjectName("laserReadLayout")
        self.deliveredPowerLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.deliveredPowerLabel.setStyleSheet("font: 75 8pt \"Arial\";")
        self.deliveredPowerLabel.setObjectName("deliveredPowerLabel")
        self.laserReadLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.deliveredPowerLabel)
        self.temperatureLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.temperatureLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.temperatureLabel.setStyleSheet("\n""font: 75 8pt \"Arial\";")
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.laserReadLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.temperatureLabel)
        self.deliveredPowerEntry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.deliveredPowerEntry.setEnabled(True)
        self.deliveredPowerEntry.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.deliveredPowerEntry.setStyleSheet("font: 75 8pt \"Arial\";")
        self.deliveredPowerEntry.setObjectName("deliveredPowerEntry")
        self.laserReadLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.deliveredPowerEntry)
        self.temperatureEntry = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.temperatureEntry.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperatureEntry.sizePolicy().hasHeightForWidth())
        self.temperatureEntry.setSizePolicy(sizePolicy)
        self.temperatureEntry.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.temperatureEntry.setStyleSheet("font: 75 8pt \"Arial\";")
        self.temperatureEntry.setText("")
        self.temperatureEntry.setObjectName("temperatureEntry")
        self.laserReadLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.temperatureEntry)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.laserReadLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.laserReadLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.laserReadLayout.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        self.deliveredPowerEntry.raise_()
        self.temperatureEntry.raise_()
        self.deliveredPowerLabel.raise_()
        self.temperatureLabel.raise_()
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(LIRGUI)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(420, 100, 111, 91))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.laserBeamLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.laserBeamLayout.setContentsMargins(0, 0, 0, 0)
        self.laserBeamLayout.setObjectName("laserBeamLayout")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.laserBeamLayout.addItem(spacerItem7)
        self.GBLabel_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.GBLabel_2.setStyleSheet("font: 75 8pt \"Arial\";")
        self.GBLabel_2.setTextFormat(QtCore.Qt.PlainText)
        self.GBLabel_2.setScaledContents(True)
        self.GBLabel_2.setObjectName("GBLabel_2")
        self.laserBeamLayout.addWidget(self.GBLabel_2, 0, QtCore.Qt.AlignHCenter)
        self.laserBeamBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.laserBeamBtn.setObjectName("laserBeamBtn")
        self.laserBeamLayout.addWidget(self.laserBeamBtn, 0, QtCore.Qt.AlignHCenter)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.laserBeamLayout.addItem(spacerItem8)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(LIRGUI)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 190, 531, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.cmdLineLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.cmdLineLayout.setContentsMargins(0, 0, 0, 0)
        self.cmdLineLayout.setObjectName("cmdLineLayout")
        self.cmdLineLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.cmdLineLabel.setObjectName("cmdLineLabel")
        self.cmdLineLayout.addWidget(self.cmdLineLabel)
        self.cmdLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.cmdLineEdit.setObjectName("cmdLineEdit")
        self.cmdLineLayout.addWidget(self.cmdLineEdit)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(LIRGUI)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 230, 541, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.responseLineLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.responseLineLayout.setContentsMargins(0, 0, 0, 0)
        self.responseLineLayout.setObjectName("responseLineLayout")
        self.responseLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.responseLabel.setObjectName("responseLabel")
        self.responseLineLayout.addWidget(self.responseLabel)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(LIRGUI)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(590, 10, 291, 25))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.IRCamTitleLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.IRCamTitleLayout.setContentsMargins(0, 0, 0, 0)
        self.IRCamTitleLayout.setObjectName("IRCamTitleLayout")
        self.IRTitleLabel = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.IRTitleLabel.setObjectName("IRTitleLabel")
        self.IRCamTitleLayout.addWidget(self.IRTitleLabel)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.IRCamTitleLayout.addItem(spacerItem9)
        self.camDisplayBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.camDisplayBtn.setObjectName("camDisplayBtn")
        self.IRCamTitleLayout.addWidget(self.camDisplayBtn)
        self.camConnectBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.camConnectBtn.setObjectName("camConnectBtn")
        self.IRCamTitleLayout.addWidget(self.camConnectBtn)
        self.verticalLayoutWidget = QtWidgets.QWidget(LIRGUI)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(590, 50, 291, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.IRCamLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.IRCamLayout.setContentsMargins(0, 0, 0, 0)
        self.IRCamLayout.setObjectName("IRCamLayout")

        self.retranslateUi(LIRGUI)
        QtCore.QMetaObject.connectSlotsByName(LIRGUI)

        ####################### Manual Layout Changes #######################
        self.deliveredPowerEntry.setFixedWidth(60)
        self.temperatureEntry.setFixedWidth(60)
        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        self.IRCamLayout.addWidget(self.canvas)
        self.guideBeamBtn.setStyleSheet('QPushButton{background-color: #ff0000; color: white;}')
        self.laserBeamBtn.setStyleSheet('QPushButton{background-color: #ff0000; color: white;}')

        ######################### GUI Functions #############################
        self.powerSlider.valueChanged.connect(self.powerSliderInput)
        self.powerReading.returnPressed.connect(self.powerReadingInput)
        self.guideBeamBtn.clicked.connect(self.startGuideBeam)
        self.laserBeamBtn.clicked.connect(self.startLaserBeam)
        self.cmdLineEdit.returnPressed.connect(self.cmdInput)
        self.camConnectBtn.clicked.connect(self.startCam)
        self.camDisplayBtn.clicked.connect(self.dispIRImg)

        ######################### QThread Functions #########################
        self.laserBoxReadings = LaserComms.readLaserBoxData()
        self.laserBoxReadings.start()
        self.laserBoxReadings.getTempData.connect(self.displayLaserTemp)
        self.laserBoxReadings.getPowerData.connect(self.displayLaserPower)

    def retranslateUi(self, LIRGUI):
        _translate = QtCore.QCoreApplication.translate
        LIRGUI.setWindowTitle(_translate("LIRGUI", "Form"))
        self.wattLabel1.setText(_translate("LIRGUI", "W"))
        self.laserTitleLabel.setText(_translate("LIRGUI", "Laser Power (0 - 500 Watts):"))
        self.GBLabel.setText(_translate("LIRGUI", "Guide Beam:"))
        self.guideBeamBtn.setText(_translate("LIRGUI", "OFF"))
        self.deliveredPowerLabel.setText(_translate("LIRGUI", "Laser Delivered Power (W):"))
        self.temperatureLabel.setText(_translate("LIRGUI", "Temperature (Celsius):"))
        self.GBLabel_2.setText(_translate("LIRGUI", "Laser Beam:"))
        self.laserBeamBtn.setText(_translate("LIRGUI", "OFF"))
        self.cmdLineLabel.setText(_translate("LIRGUI", "Command Line: "))
        self.responseLabel.setText(_translate("LIRGUI", "Response: "))
        self.IRTitleLabel.setText(_translate("LIRGUI", "IR-Camera: "))
        self.camDisplayBtn.setText(_translate("LIRGUI", "Display"))
        self.camConnectBtn.setText(_translate("LIRGUI", "Connect"))
    
    def powerSliderInput(self): # Changes laser power and adjusts display on the reading input to match
        inputPower = self.powerSlider.value()
        self.powerReading.setText(str(inputPower))
        inputPowerPercent = round((inputPower/5),1) # % is power/500
        msg = (f"SDC {str(inputPowerPercent)}")
        LaserComms.sendCmd(msg)

    def powerReadingInput(self): # Changes laser power and adjusts display on the slider to match
        inputPower = self.powerReading.text()
        self.powerSlider.setValue(int(inputPower))
        inputPowerPercent = round((int(inputPower)/5),1)
        msg = (f"SDC {str(inputPowerPercent)}")
        LaserComms.sendCmd(msg)

    def startGuideBeam(self): # Turns on and off the guide beam
        global GUIDE_BEAM_STATE
        if GUIDE_BEAM_STATE == 0:
            GUIDE_BEAM_STATE = 1
            self.guideBeamBtn.setStyleSheet('QPushButton{background-color: #00ff00; color: black;}')
            self.guideBeamBtn.setText("ON")
            LaserComms.sendCmd("ABN")
        else:
            GUIDE_BEAM_STATE = 0
            self.guideBeamBtn.setStyleSheet('QPushButton{background-color: #ff0000; color: white;}')
            self.guideBeamBtn.setText("OFF")
            LaserComms.sendCmd("ABF")

    def startLaserBeam(self): # Turns on and off the laser beam
        global LASER_BEAM_STATE
        if LASER_BEAM_STATE == 0:
            LASER_BEAM_STATE = 1
            self.laserBeamBtn.setStyleSheet('QPushButton{background-color: #00ff00; color: black;}')
            self.laserBeamBtn.setText("ON")
            LaserComms.sendCmd("EMON")
        else:
            LASER_BEAM_STATE = 0
            self.laserBeamBtn.setStyleSheet('QPushButton{background-color: #ff0000; color: white;}')
            self.laserBeamBtn.setText("OFF")
            LaserComms.sendCmd("EMOFF")

    def cmdInput(self): # Allows user to send any command found in the manual
        msg = self.cmdLineEdit.text()
        response = LaserComms.sendCmd(msg)
        self.cmdLineEdit.clear()
        self.responseLabel.setText(f"Response: {response}")

    def displayLaserTemp(self,temp):
        self.temperatureEntry.setText(temp)

    def displayLaserPower(self,power):
        self.deliveredPowerEntry.setText(power)

    def startCam(self): # Connects the IR Camera
        global CAM_CONNECT_STATE
        if CAM_CONNECT_STATE == 0:
            try:
                self.IRCam = IRCam.runCamera()
                self.IRCam.start()
                self.IRCam.getConnectState.connect(self.changeConnectState)
                self.IRCam.getImgData.connect(self.plotIRImg)
            except:
                print("Connection Failed")

    def dispIRImg(self): # Turns on the image display feed
        global PLOT_BUTTON_STATE

        if PLOT_BUTTON_STATE == 0:
            self.camDisplayBtn.setText("Pause")
            PLOT_BUTTON_STATE = 1
            print("starting feed")

        else:
            self.camDisplayBtn.setText("Display")
            PLOT_BUTTON_STATE = 0
            print("stopping feed")

    def plotIRImg(self,IRMap): # Image display feed
        global PLOT_BUTTON_STATE
        print(IRMap)

        if PLOT_BUTTON_STATE == 1:
            min = 5000 # These are the min and max values of the img array. Adjust to tune image
            max = 7000
            print(IRMap)
            self.figure.clear()
            ax = self.figure.add_subplot(111)
            ax.imshow(IRMap, vmin = min, vmax = max, interpolation = 'nearest', cmap='inferno') # Inferno can be changed to another color map
            self.canvas.draw()

        else:
            pass

    def changeConnectState(self,state): # Changes the text on the connect button once camera is successfully connected
        if state == 1:
            self.camConnectBtn.setText("Connected")
        elif state == 0:
            self.camConnectBtn.setText("Connect")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LIRGUI = QtWidgets.QWidget()
    ui = Ui_LIRGUI()
    ui.setupUi(LIRGUI)
    LIRGUI.show()
    sys.exit(app.exec_())
